### ISSUE TITLE
odd exception from node

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/snowblossom#151]
Nov 16 06:46:58 snow-usw1 node.sh[2070]: Commiting new UTXO root: d91ef515c4fa4a018612466e93273080833ecf88c0a7c2ff5bb7f9                                                                     04d0a4dd60
Nov 16 06:46:58 snow-usw1 node.sh[2070]: [2018-11-16 06:46:58]    INFO snowblossom.node.PeerLink onNext Some bs from 260                                                                     1:602:8802:2091:8024:a264:5e76:5330:2338
Nov 16 06:46:58 snow-usw1 node.sh[2070]: java.lang.RuntimeException: org.rocksdb.RocksDBException: unknown WriteBatch ta                                                                     g
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.lib.db.rocksdb.RocksDBMap.putAll(RocksDBMap.java:97)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.lib.trie.TrieDBMap.bulkSave(TrieDBMap.java:54)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.lib.trie.TrieDBBuffered.commit(TrieDBBuffered.java:34)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.lib.trie.HashedTrie.mergeIfNewRoot(HashedTrie.java:70)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.lib.UtxoUpdateBuffer.commitIfEqual(UtxoUpdateBuffer.java                                                                     :41)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.lib.Validation.deepBlockValidation(Validation.java:313)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.node.BlockIngestor.ingestBlock(BlockIngestor.java:113)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.node.PeerLink.onNext(PeerLink.java:197)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.node.PeerLink.onNext(PeerLink.java:22)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessa                                                                     ge(ClientCalls.java:406)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallL                                                                     istener.java:33)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallL                                                                     istener.java:33)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAv                                                                     ailable.runInContext(ClientCallImpl.java:526)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:12                                                                     3)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor                                                                     .java:1149)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecuto                                                                     r.java:624)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at java.lang.Thread.run(Thread.java:748)
Nov 16 06:46:58 snow-usw1 node.sh[2070]: Caused by: org.rocksdb.RocksDBException: unknown WriteBatch tag
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at org.rocksdb.RocksDB.write0(Native Method)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at org.rocksdb.RocksDB.write(RocksDB.java:602)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         at snowblossom.lib.db.rocksdb.RocksDBMap.putAll(RocksDBMap.java:92)
Nov 16 06:46:58 snow-usw1 node.sh[2070]:         ... 17 more
Nov 16 06:47:02 snow-usw1 node.sh[2070]: [2018-11-16 06:47:02]    INFO snowblossom.node.PeerLink sendCluster Sending clu                                                                     ster for 81d743cb1ca6f7a309d15a149a181b50da52bf035fbc091e9df5addc2396177f - 4 transactions
Nov 16 06:47:02 snow-usw1 node.sh[2070]: [2018-11-16 06:47:02]    INFO snowblossom.node.PeerLink sendCluster Sending clu                                                                     ster for 405fc715565d710fcff700fb15b50f144161c91c26b7e9001b3036525b3e0505 - 4 transactions
Nov 16 06:47:02 snow-usw1 node.sh[2070]: [2018-11-16 06:47:02]    INFO snowblossom.node.PeerLink sendCluster Sending clu                                                                     ster for e9d6150ed51ba90f6b1a664901b2d9af5434ed3f9fccfd982e2e0b58cd9af4cd - 4 transactions

**Comment by fireduck64** [comment]
might be related to: https://github.com/facebook/rocksdb/issues/752

**Comment by fireduck64** [comment]
Might be fixed by f1155a5a979b40156d865621b862d093e62d2d7f

**Comment by fireduck64** [comment]
Haven't seen this one in a while.
