### ISSUE TITLE
unsafe connection close

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/snowblossom#158]
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=2108, target=[2601:602:8802:2091:dc43:2ff:fe1e:5206]:2338} was not shutdown properly!!! ~*~*~*
  Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site

Note1: This is a client side
Note2: Suspect something about firewalls or timeouts involved

**Comment by ZacharyACoon** [comment]
Occurs when running gui as well:
```
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=14, target=localhost:2338} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:548)
	at snowblossom.client.StubUtil.openChannel(StubUtil.java:120)
	at snowblossom.client.StubUtil.findFastestChannelMonitor(StubUtil.java:187)
	at snowblossom.iceleaf.NodeSelectionPanel$ChannelMaintThread.runPass(NodeSelectionPanel.java:155)
	at duckutil.PeriodicThread.run(PeriodicThread.java:30)
```
