### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.g

### ISSUE THREAD

**Issue by sunk818** [snowblossomcoin/snowblossom#165]
I am using jdk8u102. I edited client.bat for Windows version. This is the error I get when I try to start the cilent.bat

```css
[2019-04-06 07:01:32]    INFO snowblossom.client.SnowBlossomClient <init> Starting SnowBlossomClient
 version 1.5.0
[2019-04-06 07:01:35]    INFO snowblossom.client.Purse checkHistory Error from server on checking address.  This is fine, but to get more accuracy on used address, have the node enable addr_index
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.g
rpc.StatusRuntimeException: UNAVAILABLE: io exception
        at duckutil.TaskMaster.getResults(TaskMaster.java:69)
        at duckutil.TaskMaster.getResults(TaskMaster.java:53)
        at snowblossom.client.SnowBlossomClient.showBalances(SnowBlossomClient.java:654)
        at snowblossom.client.SnowBlossomClient.main(SnowBlossomClient.java:61)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io
exception
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at duckutil.TaskMaster.getResults(TaskMaster.java:62)
        ... 3 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
        at snowblossom.proto.UserServiceGrpc$UserServiceBlockingStub.getNodeStatus(UserServiceGrpc.j
ava:794)
        at snowblossom.client.GetUTXOUtil.getCurrentUtxoRootHash(GetUTXOUtil.java:45)
        at snowblossom.client.GetUTXOUtil.getSpendableValidated(GetUTXOUtil.java:126)
        at snowblossom.client.GetUTXOUtil.getSpendableWithMempool(GetUTXOUtil.java:68)
        at snowblossom.client.SnowBlossomClient.getSpendable(SnowBlossomClient.java:703)
        at snowblossom.client.SnowBlossomClient$2.call(SnowBlossomClient.java:604)
        at snowblossom.client.SnowBlossomClient$2.call(SnowBlossomClient.java:593)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no furthe
r information: localhost/0:0:0:0:0:0:0:1:2338
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChanne
l.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:8
84)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused: no further information
        ... 11 more
.
Press any key to continue . . .
```

**Comment by fireduck64** [comment]
It looks like the node isn't responding to requests.  Do you have a node running on the same machine?

**Comment by sunk818** [comment]
@fireduck64 No, that was the first batch file I tried to run.

**Comment by ZacharyACoon** [comment]
If you're not running a node, the client will not be able to connect to it.
Old issue, closing.
