### ISSUE TITLE
32-bit jvm warning - just like channels

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/snowblossom#170]

**Comment by fireduck64** [comment]
Pretty clear:
Jan 23, 2020 10:43:24 PM snowblossom.node.StatusLogger setStatus
INFO: Initializing SnowBlossomNode
Jan 23, 2020 10:43:24 PM snowblossom.node.SnowBlossomNode <init>
INFO: Starting SnowBlossomNode version 1.6.0-dev
Jan 23, 2020 10:43:24 PM snowblossom.node.SnowBlossomNode loadDB
SEVERE: Java Virtual Machine is 32-bit.  rocksdb does not work with 32-bit jvm.
Jan 23, 2020 10:43:24 PM snowblossom.node.SnowBlossomNode loadDB
SEVERE: Upgrade to 64-bit JVM or set db_type=lobstack
Exception in thread "main" java.lang.RuntimeException: Needs 64-bit JVM for rocksdb
        at snowblossom.node.SnowBlossomNode.loadDB(SnowBlossomNode.java:220)
        at snowblossom.node.SnowBlossomNode.<init>(SnowBlossomNode.java:91)
        at snowblossom.node.SnowBlossomNode.<init>(SnowBlossomNode.java:76)
        at snowblossom.node.SnowBlossomNode.main(SnowBlossomNode.java:46)
