### ISSUE TITLE
Windows: Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't find dependent libraries

### ISSUE THREAD

**Issue by fireduck64** [snowblossomcoin/snowblossom#32]
C:\Users\fired\OneDrive\Desktop\snowblossom>java -jar SnowBlossomNode_deploy.jar node.conf
May 23, 2018 10:19:10 PM snowblossom.db.rocksdb.JRocksDB <init>
INFO: Loadng RocksDB with path snowdb
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\fired\AppData\Local\Temp\librocksdbjni9215880716895403884.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(Unknown Source)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at snowblossom.db.rocksdb.JRocksDB.<init>(JRocksDB.java:43)
        at snowblossom.SnowBlossomNode.loadDB(SnowBlossomNode.java:127)
        at snowblossom.SnowBlossomNode.<init>(SnowBlossomNode.java:61)
        at snowblossom.SnowBlossomNode.main(SnowBlossomNode.java:32)

https://github.com/facebook/rocksdb/issues/3307

**Comment by fireduck64** [comment]
Trying:
bcdedit /set xsavedisable 1

**Comment by fireduck64** [comment]
That didn't help

**Comment by fireduck64** [comment]
I have a workaround.

In node.conf, set:
db_type=lobstack

And use the most recent download jar file and it should work.  I brought my key value store from another project over to here.
