### ISSUE TITLE
Incorrect channel shutdown

### ISSUE THREAD

**Issue by protovist** [snowblossomcoin/snowblossom#57]
`Jun 07, 2018 10:59:58 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=io.grpc.internal.ManagedChannel$mpl-316, target=[2601:602:8802:2091:4875:7446:ce75:f5f3]:2338} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination($ returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference$<init>(ManagedChannelOrphanWrapper.java:103)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOr$hanWrapper.java:53)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOr$hanWrapper.java:44)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractMan$gedChannelImplBuilder.java:396)
        at snowblossom.node.PeerClient.<init>(PeerClient.java:20)
        at snowblossom.node.Peerage$PeerageMaintThread.connectToPeers(Peerage.j$
va:383)
        at snowblossom.node.Peerage$PeerageMaintThread.run(Peerage.java:316)`

**Comment by fireduck64** [comment]
Not sure how this is happening. Doesn't seem to break anything but should be tracked down.
