### ISSUE TITLE
Error when running pool-miner: Exception in thread "main" java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by seanspotatobusiness** [snowblossomcoin/snowblossom#94]
I tried to switch from 1.0.6 by copying my wallet and the snow and snow.db files to the folder for 1.1.2 and when I ran pool-miner.bat, this was the result: 

```
[2018-06-21 20:01:58]    INFO snowblossom.miner.FieldScan scan Not loading 10 snowblossom.10 (shai-hulud), directory not present: snow\snowblossom.10
[2018-06-21 20:01:58]    INFO snowblossom.miner.FieldScan scan Not loading 11 snowblossom.11 (avanc), directory not present: snow\snowblossom.11
Exception in thread "main" java.lang.IllegalArgumentException: Invalid host or port:  23380
        at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:480)
        at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:115)
        at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:101)
        at io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
        at io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:36)
        at snowblossom.miner.PoolMiner.subscribe(PoolMiner.java:130)
        at snowblossom.miner.PoolMiner.<init>(PoolMiner.java:109)
        at snowblossom.miner.PoolMiner.main(PoolMiner.java:49)
Caused by: java.net.URISyntaxException: Expected hostname at index 2: //:23380
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.failExpecting(Unknown Source)
        at java.net.URI$Parser.parseHostname(Unknown Source)
        at java.net.URI$Parser.parseServer(Unknown Source)
        at java.net.URI$Parser.parseAuthority(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:478)
        ... 8 more
```

**Comment by fireduck64** [comment]
I got that myself this morning and not sure why.

**Comment by seanspotatobusiness** [comment]
Should I wait for the next release or is there some way around it?

**Comment by fireduck64** [comment]
edit the config file as hard as you can.

It is probably some whitespace somewhere or something, I'm not sure.

**Comment by cluelessperson** [comment]
I got the same error in python because of whitespace.

**Comment by cluelessperson** [comment]
closing for now, assuming whitespace issue
